name: Docker Build and Push Workflow v3

on:
  push:
    branches:
      - main
      - latest
  workflow_dispatch:
    inputs:
      docker_username:
        description: 'Docker Hub Username'
        required: true
      docker_password:
        description: 'Docker Hub Password or Personal Access Token (PAT)'
        required: true
      image_name:
        description: 'Docker image name (e.g., myimage)'
        required: true
        default: 'zb'
      image_tag:
        description: 'Docker image tag (e.g., latest, v1.0)'
        required: true
        default: 'latest'
      build_option:
        description: 'Choose the build option: "dockerfile", "compose", or "custom"'
        required: true
        default: 'dockerfile'
      custom_build_command:
        description: 'Custom build command (only used when build option is "custom")'
        required: false
        default: ''

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.inputs.docker_username }}
          password: ${{ github.event.inputs.docker_password }}

      # Option 1: Build and push using a Dockerfile with build-push-action
      - name: Build and Push via Dockerfile
        if: ${{ github.event.inputs.build_option == 'dockerfile' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ github.event.inputs.docker_username }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}

      # Option 2: Build and push using Docker Compose
      - name: Build and Push via Docker Compose
        if: ${{ github.event.inputs.build_option == 'compose' }}
        run: |
          docker-compose build
          docker-compose push

      # Option 3: Run a custom build command provided by the user
      - name: Run Custom Build Command
        if: ${{ github.event.inputs.build_option == 'custom' }}
        run: |
          if [ -z "${{ github.event.inputs.custom_build_command }}" ]; then
            echo "No custom build command provided. Exiting..."
            exit 1
          else
            echo "Executing custom build command: ${{ github.event.inputs.custom_build_command }}"
            eval "${{ github.event.inputs.custom_build_command }}"
          fi
